# database.yml
# developmentとproductionで環境を分けて書いておくとよい？

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:
  socket: /tmp/mysql.sock

development: 
  <<: *default
  database: sinatra_development
